version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: laravel
        uid: 1000
    image: aromas-app
    container_name: aromas-app
    restart: unless-stopped
    working_dir: /var/www
    environment:                           # <-- NUEVO
      - TZ=America/Mexico_City             # <-- NUEVO
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
      - ./php-local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - aromas-net

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: laravel
        uid: 1000
    image: aromas-app
    container_name: aromas-scheduler
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan schedule:work
    environment:                           # <-- NUEVO
      - TZ=America/Mexico_City             # <-- NUEVO
    volumes:
      - ./:/var/www
      - ./php-local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - aromas-net
    depends_on:
      - app
      - db

  db:
    image: mysql:8.0
    container_name: aromas-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: aromas_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: aromas_pass
      MYSQL_USER: aromas_user
      TZ: America/Mexico_City              # <-- NUEVO (aquÃ­ se pone sin guion porque el formato arriba no los usa)
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - aromas-net
    command: --default-authentication-plugin=mysql_native_password

  nginx:
    image: nginx:alpine
    container_name: aromas-nginx
    restart: unless-stopped
    environment:                           # <-- NUEVO
      - TZ=America/Mexico_City             # <-- NUEVO
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - aromas-net

networks:
  aromas-net:
    driver: bridge

volumes:
  dbdata: